### PR TITLE
fix crush with the same name

### PR DESCRIPTION
**Pull request by GlodBlock**
see this https://github.com/GTNewHorizons/GT5-Unofficial/pull/697

### CODE REVIEW

**Review by mitchej123 — CHANGES_REQUESTED** [review]
This will make nei not compatible with any version of gtpp that isnt shipped with gtnh. My goal is for broad 1.7.10 compat. If you want to change the names in our fork, please have gtpp register it's handlers with imc.

**Comment by GlodBlock** [comment]
@mitchej123  done now

**Review by mitchej123 — APPROVED** [review]
Pending confirmation from Dream that it works.  Otherwise looks fine, it won't break the NEI global compat now :)

**Comment by Dream-Master** [comment]
will check ingame

**Pull request merged**
