### PR TITLE
More saner & less tedious recipes

### PR DESCRIPTION
**Pull request by ScriptedPiky**
**Time in ticks**
Quantum Anomaly: 1000 > 750
Hydrogen Ion Production: 15000 > 2500
Hydrogen Plasma: 1 > 100
Tier is LuV; unchanged (or is it IV?)

### CODE REVIEW

**Comment by miozune** [comment]
Can we also increase chances (and duration as well), especially for Quantum Anomaly? 1% is too small.
Yes IRL particle collisions are RNG, but it's bad for game design. Lucky people can cheese it, while unlucky people are pissed off.

**Comment by ScriptedPiky** [comment]
Does increasing chance to 25% and voltage tier to 7 (I think ZPM?) work? And duration in ticks? Would 500 ticks work? Or rather it's currently 750 ticks

**Comment by draknyte1** [comment]
> Can we also increase chances (and duration as well), especially for Quantum Anomaly? 1% is too small.
> Yes IRL particle collisions are RNG, but it's bad for game design. Lucky people can cheese it, while unlucky people are pissed off.

Every player I’ve seen make quantum anomalies didn’t complain, some even felt it rewarding when it finally appeared in their output bus. End game players who need several didn’t find it too costly or time consuming.

**Comment by Eranicus** [comment]
stop making endgame easyer please....  anomaly's were never a problem, its called anomaly for a reason and should be as rare as 1%

**Comment by ScriptedPiky** [comment]
I myself found it incredibly tedious, mostly since it's a 1-off kind of thing but it's so absurdly rare that it's more or less a time gate; specifically it took over a day of 4 UV paralleled Cyclotrons to get the required low amount of Anomalies (around 3-4 at the time). I could potentially make it 1% again but increasing it to UV or UHV with a somewhat short processing time

**Comment by Eranicus** [comment]
As a UHV player, I managed to build 32 mass fabricators which require these anomalies in 3-4 days time.... without any problems with 3 cyclotrons. In my opinion the chance should remain the same (1%), processing time can be decrised if you want but still not neccesary in my opinion... end game should be hard

**Comment by Steelux8** [comment]
Anomalies are supposed to be rare, and you should be able to build several Cyclotrons to get them for endgame purposes. It's unreasonable to expect it to come easily off one Cyclotron. The 1% chance is fine as it is.

**Comment by miozune** [comment]
I mean, I don't mind the total energy usage, what I'm worried about is that low chance... but I'm still at mid-ZPM and never built one, so if most of the people say fine as is, I'll follow the pioneers.

**Comment by ScriptedPiky** [comment]
> Anomalies are supposed to be rare, and you should be able to build several Cyclotrons to get them for endgame purposes. It's unreasonable to expect it to come easily off one Cyclotron. The 1% chance is fine as it is.

It's now returned to 1% and is UV tier at 25 seconds.

> I mean, I don't mind the total energy usage, what I'm worried about is that low chance... but I'm still at mid-ZPM and never built one, so if most of the people say fine as is, I'll follow the pioneers.

The most tedious part was the hydrogen ion production, as it took 15000 ticks or rather, 750 seconds at LuV, and the chances were 1.25% for each, which is what caused the enormous bottleneck to begin with. Technically, you can only use the Quantum Anomaly at UV tier-ish, though I'm not sure if 2 or more energy hatches works on the Cyclotron

**Comment by Eranicus** [comment]
> I'm not sure if 2 or more energy hatches works on the Cyclotron

They do work, i used x2 hatches per cyclotron in order to decrease prod. time while I was farming anomalies.

**Comment by ScriptedPiky** [comment]
Oh perfect! That's excellent then.

**Comment by Steelux8** [comment]
This change would also solve the last problem with the endgame solder in #196.

**Review by Steelux8 — APPROVED** [review]
Reduces the time gate on the Quantum Anomaly farm if enough energy is put in, looks good to me.

**Pull request merged**
