### PR TITLE
Now large processing factory cannot ignore low gravity condition.

### PR DESCRIPTION
**Pull request by koiNoCirculation**
Large processing factory needs a nerf, so it can't provide low gravity condition anymore.
As we known, large processing factory is unlocked in IV tier, and crystal chip is unlocked after fusion MK1, in LuV tier.
Before this change, players can just skip low-gravity condition to make chips.That's why this nerf is necessary.
Like what we have done on integrated circuit, cleanroom condition can be skipped after 2 tiers since first occurance(early/mid HV), in EV tier(for nano circuit), IV tier(for circuits, with processing array). We can add a new multi block to contain nerfed large processing array, which is used to provide low gravity condition on the earth. It should be unlocked in UV/UHV-tier.

### CODE REVIEW

**Comment by Steelux8** [comment]
> That's why this nerf is necessary

Explain why the nerf is necessary.

**Comment by Hikari1nVoid** [comment]
please show your proof of completion for this pack.

**Comment by koiNoCirculation** [comment]
@Steelux8 As I said, raw crystal chip is unlocked at LuV/Fusion MK1, but large processing factory is unlocked at IV, which invalidates this 'low gravity' setting.

**Comment by koiNoCirculation** [comment]
Processing array can't process these recipes on earth, so there's no reason for large processing factory to do that. Both of them are unlocked at IV.

**Comment by koiNoCirculation** [comment]
> please show your proof of completion for this pack.

Well, I am at middle UHV with space elevator, at least my progress is far ahead than @Dream-Master, who was at LuV / ZPM.

**Comment by Steelux8** [comment]
Is the low gravity recipe setting good for the pack? Should it be forced? Just because it has existed doesn't mean it should exist now.

**Comment by koiNoCirculation** [comment]
@Steelux8 Well, I asked about that, it still exists. And it's not planned to be removed, at least for now.

**Comment by Dream-Master** [comment]
I think we need to have some general talk. I want some emulation chip/mechanism for all multies emulate cleanroom condition's and low gravity . Without the chip /mechanism the process fail. It will affect all multies gt gt++ etc.

**Comment by koiNoCirculation** [comment]
> I think we need to have some general talk. I want some emulation chip/mechanism for all multies emulate cleanroom condition's and low gravity . Without the chip /mechanism the process fail. It will affect all multies gt gt++ etc.

I think it's a good idea. Upgrade chip seems be cool. I think it's good to unlock this conditions after 1-2 tiers after initial conditioned recipe.

**Comment by evgengoldwar** [comment]
> @Steelux8 As I said, raw crystal chip is unlocked at LuV/Fusion MK1, but large processing factory is unlocked at IV, which invalidates this 'low gravity' setting.

no rocket run -_-

**Comment by koiNoCirculation** [comment]
> > @Steelux8 As I said, raw crystal chip is unlocked at LuV/Fusion MK1, but large processing factory is unlocked at IV, which invalidates this 'low gravity' setting.
> 
> no rocket run -_-

you can just make tier 1 rocket and build space station, without going to moon XD.

**Comment by evgengoldwar** [comment]
> > > @Steelux8 As I said, raw crystal chip is unlocked at LuV/Fusion MK1, but large processing factory is unlocked at IV, which invalidates this 'low gravity' setting.
> > 
> > 
> > no rocket run -_-
> 
> you can just make tier 1 rocket and build space station, without going to moon XD.

no rocket run means not to craft rockets

**Comment by koiNoCirculation** [comment]
> > > > @Steelux8 As I said, raw crystal chip is unlocked at LuV/Fusion MK1, but large processing factory is unlocked at IV, which invalidates this 'low gravity' setting.
> > > 
> > > 
> > > no rocket run -_-
> > 
> > 
> > you can just make tier 1 rocket and build space station, without going to moon XD.
> 
> no rocket run means not to craft rockets

Well, don't care about such details. The objective of 'no-rocket run' is to complete the game without obtaining resource from other planets, at least before you have space elevator :).

**Comment by evgengoldwar** [comment]
> > > > > @Steelux8 As I said, raw crystal chip is unlocked at LuV/Fusion MK1, but large processing factory is unlocked at IV, which invalidates this 'low gravity' setting.
> > > > 
> > > > 
> > > > no rocket run -_-
> > > 
> > > 
> > > you can just make tier 1 rocket and build space station, without going to moon XD.
> > 
> > 
> > no rocket run means not to craft rockets
> 
> Well, don't care about such details. The objective of 'no-rocket run' is to complete the game without obtaining resource from other planets, at least before you have space elevator :).

The objective of 'no-rocket run' is to complete the game without craft rockets -_- not getting resources

**Comment by koiNoCirculation** [comment]
7061701c18e34ca6f465532f60f593bb

**Comment by boubou19** [comment]
Putting a machine in a dim for a chance based craft to only make the item once so you can replicate it again anywhere is not difficult, it's tedious. This is a bad game design imo, just to give a bit more uses of the space dims.

Aside from tedium, i always had issues understanding why would the first one be possible with low gravity but the rest can be done just fine? If low gravity is required for a yet to be determined process of manufacturing, why can it be bypassed after the very first item? While too much realism is bad for the game, here, it's plain bullshit.

Also, as a reminder, we rejected a similar PR for cleanroom enforcement 4 years ago, because it would be too tedious to spam cleanrooms everywhere, especially now that the endgame grew this big.

Now i am not against some modules you'd place in the multi to simulate CRs or low gravity. But as @Dream-Master said, this requires tons of discussion and planning, as well as the addition of the mechanic of modules, which is not what this PR does at all.

About no rocket runs, they aren't supported by us, it always was a meme. You can add dumb and totally inefficient recipes for this kind of runs, such that no one doing the intended progression will ever try to do the recipes, but pack changes being refused because of no rocket runs will not happen.

**Comment by Dream-Master** [comment]
Let this pr open as a reminder for a balance discussion for 2.7.0.

**Comment by koiNoCirculation** [comment]
> pack

So I made another PR to move all crystal related recipes to space station.

**Comment by koiNoCirculation** [comment]
> Putting a machine in a dim for a chance based craft to only make the item once so you can replicate it again anywhere is not difficult, it's tedious. This is a bad game design imo, just to give a bit more uses of the space dims.
> 
> Aside from tedium, i always had issues understanding why would the first one be possible with low gravity but the rest can be done just fine? If low gravity is required for a yet to be determined process of manufacturing, why can it be bypassed after the very first item? While too much realism is bad for the game, here, it's plain bullshit.
> 
> Also, as a reminder, we rejected a similar PR for cleanroom enforcement 4 years ago, because it would be too tedious to spam cleanrooms everywhere, especially now that the endgame grew this big.
> 
> Now i am not against some modules you'd place in the multi to simulate CRs or low gravity. But as @Dream-Master said, this requires tons of discussion and planning, as well as the addition of the mechanic of modules, which is not what this PR does at all.
> 
> About no rocket runs, they aren't supported by us, it always was a meme. You can add dumb and totally inefficient recipes for this kind of runs, such that no one doing the intended progression will ever try to do the recipes, but pack changes being refused because of no rocket runs will not happen.

Cleanroom is enforced from early HV to mid-IV. We can also enforce low gravity for 1-2 tiers, not forever.

**Comment by boubou19** [comment]
> Cleanroom is enforced from early HV to mid-IV. We can also enforce low gravity for 1-2 tiers, not forever.

CR is enforced until mid IV because after the game is only made of multis, not because we chose to yeet it totally. In fact, most of the endgame recipes were designed with the "CR is bypassed by multis anyways" state of mind.

It would also be inconsistent because why would a particular tech requiring low gravity but the later ones which are evolutions of it wouldn't? We could just totally skip the whole low gravity requirement just fine, progression wouldn't be impacted at all. And this is a great indicator of a poor mechanic imo.

**Comment by koiNoCirculation** [comment]
> Putting a machine in a dim for a chance based craft to only make the item once so you can replicate it again anywhere is not difficult, it's tedious. This is a bad game design imo, just to give a bit more uses of the space dims.
> 
> Aside from tedium, i always had issues understanding why would the first one be possible with low gravity but the rest can be done just fine? If low gravity is required for a yet to be determined process of manufacturing, why can it be bypassed after the very first item? While too much realism is bad for the game, here, it's plain bullshit.
> 
> Also, as a reminder, we rejected a similar PR for cleanroom enforcement 4 years ago, because it would be too tedious to spam cleanrooms everywhere, especially now that the endgame grew this big.
> 
> Now i am not against some modules you'd place in the multi to simulate CRs or low gravity. But as @Dream-Master said, this requires tons of discussion and planning, as well as the addition of the mechanic of modules, which is not what this PR does at all.
> 
> About no rocket runs, they aren't supported by us, it always was a meme. You can add dumb and totally inefficient recipes for this kind of runs, such that no one doing the intended progression will ever try to do the recipes, but pack changes being refused because of no rocket runs will not happen.

Well, if you say putting some craft to specific dim is tedious game design, I'd like to talk about bees. Indium bee requires dim Venus, and can't be crafted through gendustry :(.

**Comment by boubou19** [comment]
> Well, if you say putting some craft to specific dim is tedious game design, I'd like to talk about bees. Indium bee requires dim Venus, and can't be crafted through gendustry :(.

Bees, like crops and solars, are the kind of stuff you do once then you get forever passive incomes. It cannot be balanced properly except with an initial cost fixing the point in progression at which it is deemed correct to have them. Also this is offtopic.

**Comment by Dream-Master** [comment]
I like the idea have some space station or moon base with unique stuff you can do only there but it need to discussed and designed first to not become bad game design .

**Comment by koiNoCirculation** [comment]
> > Well, if you say putting some craft to specific dim is tedious game design, I'd like to talk about bees. Indium bee requires dim Venus, and can't be crafted through gendustry :(.
> 
> Bees, like crops and solars, are the kind of stuff you do once then you get forever passive incomes. It cannot be balanced properly except with an initial cost fixing the point in progression at which it is deemed correct to have them. Also this is offtopic.

Well, I think a space base is cool in this game. We can connect the space station to the base with EIO transformer, or with AE quantum bridge, which just requires a few extra work for players.

**Comment by koiNoCirculation** [comment]
1d91d2d75f1ca01dc4a64927e3f5ff6d
Well there are more recipes that requires low gravity added in 2.6.x.

**Comment by Divran** [comment]
If something is added that requires a space station then the bug that causes you to get yeeted up at mach 20 whenever you walk around on a space station needs to be fixed first. I've been told that using a copterpack is a workaround, but just because a workaround exist does not mean it isn't a bug, and we shouldn't need to carry around MV tier tech for the entire rest of the game for no reason other than to fly back to the space station every 3 seconds

**Comment by koiNoCirculation** [comment]
67f70c52bd2d18aba73c1c8cdbd9270f
I have applied this change to my server, and here's my space base producing crystal chips.

**Comment by NotAPenguin0** [comment]
I'll just copy paste what I wrote about this in Discord a few weeks ago that I think sums up the situation for what we want of this pretty well.

- Space station dims are awful to play in (fixable but it is an issue right now)
- This low gravity requirement for one recipe is very arbitrary (you only run it once anyway)
- Moving to a different dimension or environment for a process is a gimmick that gets old quickly, and in my opinion by LuV it's lost all it's charm and just becomes needless tedium
- IF we could in the future make a full space base useful by having entire processing chains/mainline progression things that take place in space, I'm all for it, but this is not the way to do so

**Comment by evgengoldwar** [comment]
It would be cool to see separate chemical lines not only on a space base but also on different planets, similar to Dyson

**Comment by boubou19** [comment]
> Let this pr open as a reminder for a balance discussion for 2.7.0.

This PR is only still open because it reminds Dream and I about the silliness of the space dim requirement. We won't just merge this as is. We perfectly know the issues with this system. Don't worry.

**Comment by Dream-Master** [comment]
@koiNoCirculation when gt addons are all in one more we can take care this issue

**Pull request closed without merging**
