### PR TITLE
Disable the large generator array

### PR DESCRIPTION
**Pull request by alexandre-tardif**
The multi doesn't work as intended and allows for free power generation. This PR makes them uncraftable and makes them stop working. Code is still there if someone wants to work on them at some point

### CODE REVIEW

**Review by xSkewer — APPROVED** [review]

**Comment by xSkewer** [comment]
I normally don't approve PRs but we were looking at this multi in discord and it behaves very differently from how the tooltip describes and is also overpowered because of the fuel consumption bug. It should be disabled as soon as possible and should stay disabled until it is fixed.

**Review by Dream-Master — CHANGES_REQUESTED** [review]
Please comment code out so we can see original code. For better fixing @alexandre-tardif

**Comment by alexandre-tardif** [comment]
The code is commented. I just did a comment block so it doesn't show properly on Github. Unless you mean the recipe? I can readd it and comment it if that's what's wanted

**Comment by Dream-Master** [comment]
yes the recipe. So keep the code all of it just comment it out (these parts that disable recipe etc) @alexandre-tardif

**Comment by alexandre-tardif** [comment]
Done

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
