### PR TITLE
use the proper recipe input checker instead of always reinvent the wheel

### LINKED ISSUE #10091: Cannot craft Dangote Distillus (GT++)
### Your GTNH Discord Username

miozune#9742

### Your Pack Version

2.1.2.3qf + several manual updates

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Trying to craft Dangote Distillus

### The Reality

The recipe requires unobtainable fake circuits (and it's not just visual bug but also actually uncraftable)

### Your Proposal

Implement oredicted input for Chemical Plant or add recipes for all the circuit variants.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by Glease**
Fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10091

### CODE REVIEW

**Comment by Glease** [comment]
BTW eventually we need someone to figure out why a fake circuit item would make the oredict work. I asked glod just now and he doesn't know either. It seems to "just work" for whatever reason.

**Review by miozune — APPROVED** [review]
It works, not sure why either

**Comment by GlodBlock** [comment]
the nei display is still broken

**Comment by Glease** [comment]
NEI is a separate issue and cover much more content. I have identified the source and will fix that in a separate PR.

**Pull request merged**
