### PR TITLE
New quantum anomaly texture

### PR DESCRIPTION
**Pull request by Connor-Colenso**
Full credit to Jimbno (as usual) for this texture. A much needed improvement.

q_anomaly

### CODE REVIEW

**Review by glowredman — APPROVED** [review]

**Comment by POPlol333** [comment]
Textures are good, but isn't  it bad for ram if we keep adding moving texture to rams?

**Comment by Glease** [comment]
128×128 is actually bigger than 16×384, so it's actually saving ram here

**Comment by POPlol333** [comment]
oh it all depend from that? I though the fact that the texture was moving had a point in that

**Comment by Glease** [comment]
Yeah animated takes up a bit more, but not quite as much. That ~~sprite abuse~~ unintended usage of sprite wouldn't have caused as much harm if it isn't a 400×400 res or if it was for two dozens items.

**Pull request merged**
