### PR TITLE
Allow Simple Washers to clean Purified Dusts, adds LV/HV/IV/ZPM Simple Washers

### PR DESCRIPTION
**Pull request by querns**
Purified dusts can be cleaned manually in a cauldron, so I figured that simple washers should also be able to do so.

### CODE REVIEW

**Comment by vovaksenov** [comment]
Finally after so many years lol.
Maybe you could also add crushed ore to purified ore if it hasnt been done yet?

**Comment by Dream-Master** [comment]
@querns can you remove ulv varinat and add a machine for each tier in this pr? or should we add a new one ?

**Comment by querns** [comment]
> Finally after so many years lol. Maybe you could also add crushed ore to purified ore if it hasnt been done yet?

You've been able to wash crushed ore in a simple washer for years now.

> @querns can you remove ulv varinat and add a machine for each tier in this pr? or should we add a new one ?

I went ahead and did this. There are now LV, HV, IV, and ZPM simple washers. I removed the recipe for the ULV simple washer, and adjusted its tooltip to inform about it no longer being craftable:

image

However, I didn't remove it entirely. Users will continue to have their old ULV washers, but won't be able to make new ones.

One minor note: NEI won't be particularly well-sorted for these. Since the items used sequential metadata values for the MV/EV/LuV/UV washers, I had to add the new washers further down the line. I don't know if there's a way around this, so it'll just have to be slightly confusing unless someone knows how to manually adjust sorting in NEI.

**Comment by vovaksenov** [comment]
> You've been able to wash crushed ore in a simple washer for years now.

Lmao sorry, i must have confused this with something else 😆

**Review by Steelux8 — APPROVED** [review]

**Pull request merged**
