### PR TITLE
Add Indalloy_140 mixer/EBF recipe

### PR DESCRIPTION
**Pull request by Elisis**

### CODE REVIEW

**Comment by chochem** [comment]
adding mixer recipes to alloys sounds pretty boring and simplifying. Is that really needed?

**Comment by GTNHAfx237v7** [comment]
Seconded, it’s made in the ABS at a reasonable speed already.

**Review by Connor-Colenso — CHANGES_REQUESTED** [review]
Unnecessary. ABS is sufficient as others have noted.

**Comment by Steelux8** [comment]
Do not set "uses Blast Furnace" to "true" on Indalloy, that is for auto-generating the recipe and it will have different recipe times based on whether or not CoreMod is loaded. I've fixed this already.

Also, as mentioned before, mixer recipe is unnecessary and an oversimplification. At the very least, it should be much slower than the ABS recipe and a higher tier.

**Comment by Elisis** [comment]
> Unnecessary. ABS is sufficient as others have noted.

And others have argued against 🙄

**Comment by chochem** [comment]
> > Unnecessary. ABS is sufficient as others have noted.
> 
> And others have argued against 🙄

what is your argument then? that was my question above.

**Comment by Dream-Master** [comment]
set it to draft until we find a way all people happy

**Comment by draknyte1** [comment]
Unnecessary. ABS is sufficient as others have noted.

Stop trying to remove the use of an entire mod. It’s gated behind the ABS, it should stay that way. It’s like me adding recipes to circumvent the CAL or some other multi with one job. This should be closed.

**Pull request closed without merging**
