### PR TITLE
Fix the speed of the chemplant (again)

### PR DESCRIPTION
**Pull request by chochem**
Yes, I fixed it a year ago. But it has since been broken again, this time in the other direction. :P

Specifically it was broken here: https://github.com/GTNewHorizons/GTplusplus/pull/697

### CODE REVIEW

**Comment by HoleFish** [comment]
Can't we just delete this method and do a copypaste of pyrolyse oven code?

**Comment by chochem** [comment]
never looked at pyro, whats better about it?

**Comment by HoleFish** [comment]
Pyro one is shorter (and clear):
`setSpeedBonus(2f / (1 + coilHeat.getTier()));`
In chemplant it would be like `setSpeedBonus(2f / (1 + mCoilTier));` or smth

**Comment by chochem** [comment]
done.

**Review by HoleFish — APPROVED** [review]

**Pull request merged**
