### PR TITLE
Move sources and resources

### PR DESCRIPTION
**Pull request by SinTh0r4s**
Redid the migration. Was quicker

### CODE REVIEW

**Comment by SinTh0r4s** [comment]
> Why is Buildcraft in here? I've never had it as a dep.

A quick project search reveals the reason: https://github.com/GTNewHorizons/GTplusplus/blob/57482f25b35107797adf56d8f523c43bb0ff0748/src/Java/gtPlusPlus/xmod/forestry/bees/tileentities/TileDenseBeeHouse.java#L20

Maybe someone else added it.

**Comment by draknyte1** [comment]
> > Why is Buildcraft in here? I've never had it as a dep.
> 
> A quick project search reveals the reason:
> 
> https://github.com/GTNewHorizons/GTplusplus/blob/57482f25b35107797adf56d8f523c43bb0ff0748/src/Java/gtPlusPlus/xmod/forestry/bees/tileentities/TileDenseBeeHouse.java#L20
> 
> Maybe someone else added it.

That code isn’t even used, might just remove it.

**Comment by boubou19** [comment]
3.3k files changed? this won't make it.

**Comment by bombcar** [comment]
> 3.3k files changed? this won't make it.

most of them are file moves but yeah, I can't even get GitHub to load the list.

**Comment by SinTh0r4s** [comment]
> > > Why is Buildcraft in here? I've never had it as a dep.
> > 
> > 
> > A quick project search reveals the reason:
> > https://github.com/GTNewHorizons/GTplusplus/blob/57482f25b35107797adf56d8f523c43bb0ff0748/src/Java/gtPlusPlus/xmod/forestry/bees/tileentities/TileDenseBeeHouse.java#L20
> > 
> > Maybe someone else added it.
> 
> That code isn’t even used, might just remove it.

There is also a use in `tPlusPlus.xmod.gregtech.api.items.Gregtech_MetaTool`. And I cannot easily remove that.

**Comment by draknyte1** [comment]
Isn’t that declared via an optional interface? 

If not I can probably reorganise class hierarchy. But I don’t believe GT ever had it as a hard dep.

**Comment by SinTh0r4s** [comment]
> Isn’t that declared via an optional interface?
> 
> If not I can probably reorganise class hierarchy. But I don’t believe GT ever had it as a hard dep.

That is probably a good idea. But we should do that in another PR. Just remove the hard dep once done :)

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
