### PR TITLE
Disable autocrafter

### PR DESCRIPTION
**Pull request by kuba6000**
Disable autocrafter to prevent duplication bug and overall bad design.
@Dream-Master

### CODE REVIEW

**Comment by Prometheus0000** [comment]
I don't think people will be happy with that. And if you're going to disable it, you should mention it in the quest. Also, if you're disabling it, why bother changing TT text?

**Comment by Pxx500** [comment]
> I don't think people will be happy with that. And if you're going to disable it, you should mention it in the quest. Also, if you're disabling it, why bother changing TT text?

There is a very serious duplication bug with this machine I'm not sure whether I should tell how to replicate it, only crafter is disabled tho so I don't think people will be that angry

**Comment by boubou19** [comment]
send me or any team member on discord in private the way of duplicating stuff so we can try to fix it instead of disabling it.

**Comment by Pxx500** [comment]
@boubou19 were you able to replicate the duplication bug?

**Review by GTNH-Colen — APPROVED** [review]

**Review by boubou19 — APPROVED** [review]

**Pull request merged**
