### PR TITLE
Reduce MT Sunnarium recipe time to 30s at EV

### PR DESCRIPTION
**Pull request by xSkewer**
Brings it closer to other sunnarium sources and the old MT.

### CODE REVIEW

**Comment by GTNHAfx237v7** [comment]
Very nice!

**Review by Connor-Colenso — APPROVED** [review]

**Comment by Dream-Master** [comment]
How much eu it use ?

**Comment by xSkewer** [comment]
1152000m eu at base

**Comment by Dream-Master** [comment]
Orginal recipe have 10 mio Eu not 1 so far I remember.

**Comment by GTNHAfx237v7** [comment]
Yes it did have 10Million total eu in the single block. But you could dump any voltage and amperage into it. The molecular transformer can only accept 1A of any voltage. The calculation here is based on 10 million eu at ZPM voltage (about 76 ticks).

**Comment by Connor-Colenso** [comment]
It is 600\*1920\*20 = 23m EU. 2x the old amount so can we merge this? Thanks

**Comment by GTNHAfx237v7** [comment]
600 ticks not seconds

**Comment by Connor-Colenso** [comment]
Ah fair point. Was the original recipe 10m EU for a sunnarium piece or full sunnarium blob?

**Comment by GTNHAfx237v7** [comment]
A single sunnarium piece.

**Pull request merged**
