### PR TITLE
Pikyonium64B slight material adjustment

### PR DESCRIPTION
**Pull request by ScriptedPiky**
Slightly adjusts them. Are these materials correct? Hope it didn't drastically alter too much. Is this even okay to do for the most part?

### CODE REVIEW

**Comment by draknyte1** [comment]
Why?

The only aspect of it that *would potentially* be adjusted is the Ytterbium but that's another story.

**Comment by ScriptedPiky** [comment]
I just thought of updating the materials within slightly or changing them up. Though for Ytterbium I don't know what the state of that is but am open to adjusting that if needed

**Comment by bombcar** [comment]
See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9105 for some recent discussions

**Comment by draknyte1** [comment]
Unless there’s a necessary reason to change an alloy, then no.

**Comment by draknyte1** [comment]
Imma just close this as it doesn’t really server any purpose.

**Pull request closed without merging**
