### PR TITLE
radhatch compact

### PR DESCRIPTION
**Pull request by GlodBlock**
make rad hatch accept a2's radioactive material

### CODE REVIEW

**Review by draknyte1 — COMMENTED** [review]
Cyclic dependency with BW isn’t favourable. Plus the support should be added there anyway?

**Comment by GlodBlock** [comment]
it is only a load check so there is no cyclic dependency

**Comment by draknyte1** [comment]
> it is only a load check so there is no cyclic dependency

It depends on BW classes and from memory BW already depends on GT++. Why not just add this to BW?

**Comment by Dream-Master** [comment]
@GlodBlock @draknyte1 is this possible and why it would be better ?

**Comment by draknyte1** [comment]
RadHatch is part of BW and if it wants to support content from other mods it already has as a dependency, it makes the most sense to put it there.

**Comment by GlodBlock** [comment]
will be moved to coremod

**Pull request closed without merging**
