### PR TITLE
fix frame box and block cant localized

### PR DESCRIPTION
**Pull request by iouter**
it use %material now too.

and fluid in the cell can read the fluid key instead of adding more keys.

### CODE REVIEW

**Review by eigenraven — CHANGES_REQUESTED** [review]
Does this work if you switch languages while the game is running? You shouldn't keep translated names in block classes, they should only ever appear clientside. Also in some languages you can't just substitute the material name, because of declension. E.g. in polish: iron is "żelazo", while block of iron is "blok żelaza" (o -> a has to change), so there should be separate translations for the full names.

**Comment by iouter** [comment]
> Does this work if you switch languages while the game is running?

gregtech.lang does not depend on the language, only on itself.

> You shouldn't keep translated names in block classes, they should only ever appear clientside.

could this cause any problems?

> Also in some languages you can't just substitute the material name, because of declension. E.g. in polish: iron is "żelazo", while block of iron is "blok żelaza" (o -> a has to change), so there should be separate translations for the full names.

i know russian also has this problem, maybe consider setting the automatic writing of %material through a config. i don't know if there can be a more general solution instead of having translators translate one by one.

**Review by eigenraven — APPROVED** [review]
I guess the problems are with GT's api and would have to be solved there, in that case I think this PR is fine as-is.

**Comment by iouter** [comment]
which problem?

**Pull request merged**
