### PR TITLE
GTpp machines pa fix

### PR DESCRIPTION
**Pull request by BlueWeabo**
Makes it possible for simple washer and dehydrator to work in the PA again, with the new PA changes
Requires: https://github.com/GTNewHorizons/GT5-Unofficial/pull/1272 to be merged

### CODE REVIEW

**Review by draknyte1 — CHANGES_REQUESTED** [review]
Dehydrator is intentionally not supported in PAs.

**Comment by BlueWeabo** [comment]
How is it not internally supported by the PA?

**Comment by draknyte1** [comment]
It has a multi that’s gated appropriately.

**Comment by BlueWeabo** [comment]
Then why do single block dehydrators exist?

**Comment by draknyte1** [comment]
For recipes pre ZPM?
Of which dehydrators cover up to. 

Vacuum furnace is dehydrator multi, it should be the only option beyond singles. Why support has never been added, it is intentional.

**Comment by BlueWeabo** [comment]
I have only made the PA possible to do the SB dehydrator recipes, from what I tested it is not possible to do the MB recipes.

**Comment by draknyte1** [comment]
> I have only made the PA possible to do the SB dehydrator recipes, from what I tested it is not possible to do the MB recipes.

Because the vacuum furnace has two modes, One for dehydration. PA should not do dehydration, simple.

**Comment by BlueWeabo** [comment]
If you could, can you point towards the issue, where the dehydrator was not allowed to be made put in the Processing Array? From what I know, it wasn't put there because of it's tiers are handled in its unlocalized name. Not to mention that currently it only works up to the HV recipes, pretty sure most of them are better than HV, as it only does the basic dehydrators and not the chemical+vacuumfurnace.

**Comment by draknyte1** [comment]
> If you could, can you point towards the issue, where the dehydrator was not allowed to be made put in the Processing Array? From what I know, it wasn't put there because of it's tiers are handled in its unlocalized name. Not to mention that currently it only works up to the HV recipes, pretty sure most of them are better than HV, as it only does the basic dehydrators and not the chemical+vacuumfurnace.

I intentionally never added support to the PA when I added the simple washer are there are dehydrators past HV and most recipes require those. You should be using low heat mode in the Utupu Tanari if you want parallel processing. There is no ticket, it’s a design choice. 

Not everything belongs in the PA.

**Comment by Glease** [comment]
To put it other way, for alk, not allowing dehydrator in PA is not a __technical limitation__, but a __game design consideration__.

**Comment by BlueWeabo** [comment]
Alright. I have removed it.

**Review by draknyte1 — APPROVED** [review]

**Pull request merged**
