### PR TITLE
fix 9 in 1 desc

### PR DESCRIPTION
**Pull request by bombcar**
Update the Nine in One to show all nine machines.

### CODE REVIEW

**Review by draknyte1 — CHANGES_REQUESTED** [review]
Why change the Lang file?

You didn’t update the book. It’s in BookHandler.

**Comment by bombcar** [comment]
> Why change the Lang file?
> 
> You didn’t update the book. It’s in BookHandler.

I'll update the book, the Lang file was to get it to stop complaining about invalid lines

**Comment by draknyte1** [comment]
> > Why change the Lang file?
> > You didn’t update the book. It’s in BookHandler.
> 
> I'll update the book, the Lang file was to get it to stop complaining about invalid lines

// are comments though?

**Comment by bombcar** [comment]
InteliJ doesn't like them:

image

but is fine with #:

image

**Comment by bombcar** [comment]
The book handler is already correct ?

image

**Comment by draknyte1** [comment]
> InteliJ doesn't like them:
> 
> image
> 
> but is fine with #:
> 
> image

We don’t all use IntelliJ (I don’t even use my IDE for Lang files). Don’t think we should change things that your IDE is complaining about when others may not. 

Guess I did the book ages ago then.

**Comment by bombcar** [comment]
If I'm reading the language specification correctly, only # and ! are considered comments, the rest just parse incorrectly:

> A natural line that contains only white space characters is considered blank and is ignored. A comment line has an ASCII '#' or '!' as its first non-white space character; comment lines are also ignored and do not encode key-element information. In addition to line terminators, this format considers the characters space (' ', '\u0020'), tab ('\t', '\u0009'), and form feed ('\f', '\u000C') to be white space.

https://docs.oracle.com/javase/8/docs/api/java/util/Properties.html#load-java.io.Reader-

But - I can revert

**Comment by draknyte1** [comment]
I guess you should just remake this now all the files have been moved. It’s cleaner for commit history & won’t have merge conflicts. 

As for comments in the Lang files, MC doesn’t care. Java comments start with // and all the other Lang files also use //. Might as well just keep it consistent.

**Pull request closed without merging**
