### PR TITLE
Doot doot doo

### PR DESCRIPTION
**Pull request by draknyte1**
Actually remove MT recipes from single.
Added extra safety to ED recipe generation.
Added support to the Large Sifter to use Fluid Hatches.
Fixed Height check of Distillus.

### CODE REVIEW

**Comment by Steelux8** [comment]
GregtechMeta_MultiBlockBase needs to be reviewed, I'm not sure which changes to keep between this PR and #198.
GregtechMetaTileEntity_IndustrialMolecularTransformer.java - #151.
GregtechMetaTileEntity_Adv_DistillationTower.java - #215.
GregtechMTE_ElementalDuplicator.java - #222.
GregtechMTE_FrothFlotationCell.java - #198.
GregtechMetaTileEntityTreeFarm.java  - #206.
GregtechMetaTileEntity_LargeRocketEngine.java - #119.
GregtechMTE_AlgaePondBase.java - #198.
GregtechMTE_ChemicalPlant.java - #169.

**Comment by Steelux8** [comment]
I have checked 45 out of the 91 changed files, up to the Chemical Plant, but the merge conflicts came back for some reason and there are even more than before. I'm leaving this for Alk to fix.

**Comment by kuba6000** [comment]
Fixed conflicts.

**Comment by Dream-Master** [comment]
If somone want to start working on MK5 please do a new pr.

**Pull request closed without merging**
