### PR TITLE
Remove Australia dimension and associated world gen, mobs etc.

### PR DESCRIPTION
**Pull request by Connor-Colenso**
See title, tested in full pack. Loads fine.

### CODE REVIEW

**Comment by boubou19** [comment]
what happens if previously generated australia is loaded with this GT++ version? nothing? a crash?

**Comment by Dream-Master** [comment]
Australian don’t like this change :trollface:

**Comment by Connor-Colenso** [comment]
> what happens if previously generated australia is loaded with this GT++ version? nothing? a crash?

I believe the dimension may load but any dim specific blocks will be deleted. I'm not 100% sure but given it's impossible to access this dimension without very lategame equipment (that was never intended to be used that way) it's not a big deal. Server owners can just delete the file if they really want to be 100% sure.

**Review by Steelux8 — APPROVED** [review]
I'm going to trust that this isn't going to cause problems on worlds where Australia was already generated, rare as they may be.

**Pull request merged**
