### PR TITLE
Put Multiblock Sifter to HV

### PR DESCRIPTION
**Pull request by Dream-Master**
image

### CODE REVIEW

**Comment by GTNH-Colen** [comment]
Why though?

**Comment by draknyte1** [comment]
Doesn't make any sense, it's still using a MV/HV material and this multi is not meant to be IV tier like the rest.

**Comment by Dream-Master** [comment]
we can discuss to move it to HV but i want this device stay in one tier and use all items from this tier

**Comment by draknyte1** [comment]
It already was HV...

**Comment by Dream-Master** [comment]
Now the circuits hv as well so the cables

**Review by draknyte1 — APPROVED** [review]

**Pull request merged**
