### PR TITLE
Make Chemplant Mv and use mv materials

### PR DESCRIPTION
**Pull request by Dream-Master**
Make Chemplant Mv and use mv materials

### CODE REVIEW

**Review by draknyte1 — COMMENTED** [review]
It’s meant to be made before MV, if you’re a masochist. Why tier it later when it has recipes for lower tiers?

**Comment by Dream-Master** [comment]
no one need chemplant before mv. this multi is huge i didnt not know anyne have this device in LV.

**Comment by chochem** [comment]
> It’s meant to be made before MV, if you’re a masochist. Why tier it later when it has recipes for lower tiers?

didnt it already need MV parts and power? this more make the recipe more consistent and not half LV/half MV

**Review by Steelux8 — CHANGES_REQUESTED** [review]
This PR needs a purpose. Why is this change made? Is there a need for this change?

**Comment by boubou19** [comment]
the purpose of this is simple: adding consistancy to some weird crafts. if there is no use before mv then it should be mv. There is literally no reason to craft it before so it shouldn't be a significant change anyways.

**Review by boubou19 — APPROVED** [review]

**Comment by draknyte1** [comment]
> the purpose of this is simple: adding consistancy to some weird crafts. if there is no use before mv then it should be mv. There is literally no reason to craft it before so it shouldn't be a significant change anyways.

Except it has LV recipes? 🤔
Cause ya know, Algae farm.

**Comment by POPlol333** [comment]
Does Algae have even a use in LV ? I literally used them first time in UV-ish

**Comment by Steelux8** [comment]
I didn't dislike the recipes. The Algae Farm can be effectively MV, I suppose.

**Pull request merged**
