### PR TITLE
Decreased ABS min. case count from 10 to 5

### PR DESCRIPTION
**Pull request by minecraft7771**
As discussed in github, decrease the minimum amount of casings in the ABS from 10 to 5 to go with the change of the new input seperation function.

### CODE REVIEW

**Comment by draknyte1** [comment]
I love that people are just changing how the ABS works because it was intentionally inconvenient… it was intended from the start to use one per alloy or circuit. 🤷🏻‍♀️🤷🏻‍♀️

**Comment by minecraft7771** [comment]
People also tie the alloys into the main progression more and more so its no suprise that players want changes like this.

**Comment by draknyte1** [comment]
> People also tie the alloys into the main progression more and more so its no suprise that players want changes like this.

Anyone who needs more than 1 can afford to craft and automate them. This does nothing beyond making things more convenient for later game players.

**Comment by POPlol333** [comment]
It's not about being able to afford another ABS, machine spaming is bad game design, and unfortunately already too present in late game

**Comment by draknyte1** [comment]
> It's not about being able to afford another ABS, machine spaming is bad game design, and unfortunately already too present in late game

Nobody is spamming them. At most you’d only ever need 8 to automate every alloy. The ABS should *not* allow multiple input buses, even 2 goes against the design principles of the multi.

**Comment by POPlol333** [comment]
We *might* not have the same definition then, 8 of the exact same machin for fundamentally the same objectives is machines spaming for me

**Comment by draknyte1** [comment]
> We _might_ not have the same definition then, 8 of the exact same machin for fundamentally the same objectives is machines spaming for me

Still ends up being less than most other multiblocks. 🤷🏻‍♀️

**Comment by draknyte1** [comment]
The solution isn’t to change the ABS anyway. It’s make an XL or advanced version that solves the need and is actually expensive for people who think they need it.

**Comment by minecraft7771** [comment]
I think a mega version is on the todo list of @Steelux8. If he one day does it we could move all this logic to there

**Comment by draknyte1** [comment]
It’s being done.

**Comment by Connor-Colenso** [comment]
GT++ isn't your personal thiefdom anymore Alk, you don't have the authority to arbitrarily close tickets without more discussion.

**Comment by Dream-Master** [comment]
If a MEGA ABS happen some day we can re desing it.

**Comment by draknyte1** [comment]
> GT++ isn't your personal thiefdom anymore Alk, you don't have the authority to arbitrarily close tickets without more discussion.

I can when I’m implementing the alternative. The discussion was had, you just weren’t involved.

**Comment by repo-alt** [comment]
ABS can be easily automated using a microcontroller, since all the alloys are distinguished by the circuit number equal to the number of components. At least I had no problems with it yet. At late game you would need many of them anyway, or, as suggested, a "mega" version.

**Comment by Dream-Master** [comment]
@draknyte1 ETA for the ABS ?

**Comment by Dream-Master** [comment]
the mega version

**Comment by Connor-Colenso** [comment]
@draknyte1 A ticket being open for 20 minutes is not sufficient to qualify for a "discussion". If you do finish a mega ABS then please open a new PR and revert this (if it even gets merged). You have already been removed as a GT++ repo admin, please do not force me to remove you as a member of the GTNH org for continued perm abuse. Thank you.

**Comment by draknyte1** [comment]
> @draknyte1 A ticket being open for 20 minutes is not sufficient to qualify for a "discussion". If you do finish a mega ABS then please open a new PR and revert this (if it even gets merged). You have already been removed as a GT++ repo admin, please do not force me to remove you as a member of the GTNH org for continued perm abuse. Thank you.

@Steelux8 have already discussed this, it's basically done. Stop being a wanker.   
I was never a repo admin here, lol.

**Comment by draknyte1** [comment]
Once the structure code is added, this is ready to merge - https://github.com/GTNewHorizons/GTplusplus/pull/293

**Comment by chochem** [comment]
that PR was on some version where the multi was broken and the PR was never functional. better be careful with resolving/merging.

**Comment by Dream-Master** [comment]
ok i`ll merge this now because mega abs isnt in the pack yet. We can discuss it futher when mega abs is ready,

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
