### PR TITLE
Chunkloader code rework

### LINKED ISSUE #9944: [GT++] Chunkloader MK I~III doesn't work.
### Your GTNH Discord Username

ENNISHIBUYA#3552

### Your Pack Version

2.1.2.3 QF

### Your Server

Single-player

### Type of Server

Single Player

### Your Expectation

I need a single-block machine that loads more chunks. (obviously, the world anchor loading range is not large, and it is also inconvenient)

### The Reality

But in practice, it doesn't work.   The machine is inactive.

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by minecraft7771**
The code of the chunkloaders was a mess which I couldn't fix so I remodeled it after the code from Railcraft chunkloaders and now they work as intended.

Side note: the high tier chunkloaders are advertisted as loading up to 225 chunks, though if not changed the default parameters of `forge.cfg` will limit this greatly, this is now reflected ingame as the tooltip will be limited to the actual max amount

Fixes https://github.com/GTNewHorizons/GTplusplus/issues/81
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9944

### CODE REVIEW

**Comment by repo-alt** [comment]
Looks like Alk copypasted the first version of GT_ChunkManager and didn't bother to pull the fixes later. It would probably lead to less code duplication to extend it for the "anchors" implementation, but adapting RC anchors code is also ok.

**Review by repo-alt — APPROVED** [review]

**Comment by TheInfamousAlk** [comment]
> Looks like Alk copypasted the first version of GT_ChunkManager and didn't bother to pull the fixes later.

I definitely did not do this.

**Comment by BritishCynic** [comment]
> > Looks like Alk copypasted the first version of GT_ChunkManager and didn't bother to pull the fixes later.
> 
> I definitely did not do this.

Nobody is saying you did. We have a developer who goes by Alk as shorthand for their online nickname. I'm mystified as to why you thought we were referring to you in the first place.

**Comment by TheInfamousAlk** [comment]
> > > Looks like Alk copypasted the first version of GT_ChunkManager and didn't bother to pull the fixes later.
> > 
> > 
> > I definitely did not do this.
> 
> Nobody is saying you did. We have a developer who goes by Alk as shorthand for their online nickname. I'm mystified as to why you thought we were referring to you in the first place.

I don't think I've ever mystified anyone before, so I'll count that as a win in my book!

**Comment by draknyte1** [comment]
> > Looks like Alk copypasted the first version of GT_ChunkManager and didn't bother to pull the fixes later.
> 
> I definitely did not do this.

You could never be me, The real Alkalus.

**Pull request merged**
