### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by Connor-Colenso**
Removes a bunch of useless junk that either outright crashes the game or has no texture/use. Also updates the textures of  many things. All texture credits go to Jimbo, as is noted in the pack README update.

### CODE REVIEW

**Review by draknyte1 — DISMISSED** [review]
Why remove the fire maker and food items? They exist and work as intended…

**Comment by Connor-Colenso** [comment]
> Why remove the fire maker and food items? They exist and work as intended…

Not sure I'd classify it not even having a texture/recipe as working as intended but ok.
Screenshot 2022-07-12 at 02 23 23

As for the food, it's not even craftable, the texture does not fit the standard MC style and is general unneeded bloat. We need to clean up the fork of this mod and integrate it better with the pack. This is a step towards that goal

**Comment by Dream-Master** [comment]
re add the human flesh :). Only not working and not textured items can be removed.

**Comment by draknyte1** [comment]
> > Why remove the fire maker and food items? They exist and work as intended…
> 
> Not sure I'd classify it not even having a texture/recipe as working as intended but ok. Screenshot 2022-07-12 at 02 23 23
> 
> As for the food, it's not even craftable, the texture does not fit the standard MC style and is general unneeded bloat. We need to clean up the fork of this mod and integrate it better with the pack. This is a step towards that goal

Fire pit != Basic Fire Maker. 
one is a block, one is an item.

**Comment by Dream-Master** [comment]
> > > Why remove the fire maker and food items? They exist and work as intended…
> > 
> > 
> > Not sure I'd classify it not even having a texture/recipe as working as intended but ok. Screenshot 2022-07-12 at 02 23 23
> > As for the food, it's not even craftable, the texture does not fit the standard MC style and is general unneeded bloat. We need to clean up the fork of this mod and integrate it better with the pack. This is a step towards that goal
> 
> Fire pit != Basic Fire Maker. one is a block, one is an item.

even if there is a difference why not hide items have no texture ?

**Comment by draknyte1** [comment]
> > > > Why remove the fire maker and food items? They exist and work as intended…
> > > 
> > > 
> > > Not sure I'd classify it not even having a texture/recipe as working as intended but ok. Screenshot 2022-07-12 at 02 23 23
> > > As for the food, it's not even craftable, the texture does not fit the standard MC style and is general unneeded bloat. We need to clean up the fork of this mod and integrate it better with the pack. This is a step towards that goal
> > 
> > 
> > Fire pit != Basic Fire Maker. one is a block, one is an item.
> 
> even if there is a difference why not hide items have no texture ?

It has a texture and works fine, for years. 🤦🏻‍♀️

**Comment by Dream-Master** [comment]
> > > > > Why remove the fire maker and food items? They exist and work as intended…
> > > > 
> > > > 
> > > > Not sure I'd classify it not even having a texture/recipe as working as intended but ok. Screenshot 2022-07-12 at 02 23 23
> > > > As for the food, it's not even craftable, the texture does not fit the standard MC style and is general unneeded bloat. We need to clean up the fork of this mod and integrate it better with the pack. This is a step towards that goal
> > > 
> > > 
> > > Fire pit != Basic Fire Maker. one is a block, one is an item.
> > 
> > 
> > even if there is a difference why not hide items have no texture ?
> 
> It has a texture and works fine, for years. 🤦🏻‍♀️

ingame maybe(never test it) but why it show up in the nei menu. So it would be nice items that not have a texture render in nei be displayed with this "missing texture" Texture.

**Comment by Pnc6lx** [comment]
> > > > > > Why remove the fire maker and food items? They exist and work as intended…
> > > > > 
> > > > > 
> > > > > Not sure I'd classify it not even having a texture/recipe as working as intended but ok. Screenshot 2022-07-12 at 02 23 23
> > > > > As for the food, it's not even craftable, the texture does not fit the standard MC style and is general unneeded bloat. We need to clean up the fork of this mod and integrate it better with the pack. This is a step towards that goal
> > > > 
> > > > 
> > > > Fire pit != Basic Fire Maker. one is a block, one is an item.
> > > 
> > > 
> > > even if there is a difference why not hide items have no texture ?
> > 
> > 
> > It has a texture and works fine, for years. 🤦🏻‍♀️
> 
> ingame maybe(never test it) but why it show up in the nei menu. So it would be nice items that not have a texture render in nei be displayed with this "missing texture" Texture.

basic fire starter have texture
image
and in game it show as it

**Comment by tommy307507** [comment]
image
In case that there's confusion, Pnc6Ix is asking about this change, unrelated to firepit mentioned above.

**Pull request closed without merging**
