### PR TITLE
overclock

### PR DESCRIPTION
**Pull request by Dream-Master**

### CODE REVIEW

**Comment by Dream-Master** [comment]
@skizzerz maybe you able to complete the change to us branch ?

**Comment by minecraft7771** [comment]
@BlueWeabo is working on integrate it already

**Comment by skizzerz** [comment]
@Dream-Master sorry just tweaked my github notification settings so I'll see these more quickly in the future (can also ping me on the GTNH discord: `@Lehran#0605`). I stalled on this due to the mention that it was being integrated into a more general thing, but if we want to have this in the meantime (not sure what the status on the general thing is), I can look into rebasing this to fix the conflicts and getting it tested locally.

**Comment by Dream-Master** [comment]
You mentioned that code so I thought we can add this in Gtnh . If you like just finish it /complete .

**Comment by BlueWeabo** [comment]
I was working on it on [this](https://github.com/GTNewHorizons/GT5-Unofficial/pull/1657) pull request so that every addon that depends on gt5u can use a method to calculate it parallels with void protection or without. It has been mostly tested and it works

**Comment by Dream-Master** [comment]
@skizzerz we make a new pr

**Pull request closed without merging**
