### PR TITLE
Add RawOre items and processing

### PR DESCRIPTION
**Pull request by Ethryan**
depends on: [#2502](https://github.com/GTNewHorizons/GT5-Unofficial/pull/2502)

### CODE REVIEW

**Comment by Ethryan** [comment]
??

**Comment by Caedis** [comment]
Dream is reworking some branches i think

**Comment by Dream-Master** [comment]
please not use dev branch @Ethryan 
i used it for nightly tests. i rename your branch and open a new pr

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GTplusplus/pull/879

**Comment by Caedis** [comment]
that makes sense

**Comment by Ethryan** [comment]
Ok

**Pull request closed without merging**
