### PR TITLE
Fix wrong variable used for overclock

### LINKED ISSUE #10180: Large Processing Factory does not accept multiple Energy Hatches to perform higher voltage recipe
### Your GTNH Discord Username

miozune#9742

### Your Pack Version

2.1.2.2qf2

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Try to perform recipe `Glowing Coral -> Sunnarium Dust (7680 EU/t)` by Large Processing Factory with 2 EV Energy Hatches attached.

### The Reality

The machine doesn't start. I then replaced 2 EV Energy Hatches with 1 IV Energy Hatch, and it worked, so it's not an issue with configuration.

### Your Proposal

Fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by miozune**
Fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10180

### CODE REVIEW

**Review by eigenraven — APPROVED** [review]

**Comment by draknyte1** [comment]
If you only applied this fix to two classes, I’m going to go out on a whim and say you’ve missed lots. There are *many* multis that will have this issue as there’s about 10 variations of the base multi checkRecipe.

**Comment by Dream-Master** [comment]
@miozune @kubasz

**Comment by miozune** [comment]
I checked all overrides for `checkRecipeGeneric(ItemStack[] aItemInputs, FluidStack[] aFluidInputs, int aMaxParallelRecipes, int aEUPercent, int aSpeedBonusPercent, int aOutputChanceRoll)` and `checkRecipeGeneric(ItemStack[] aItemInputs, FluidStack[] aFluidInputs, int aMaxParallelRecipes, int aEUPercent, int aSpeedBonusPercent, int aOutputChanceRoll, GT_Recipe aRecipe)`, and no problem found for `tEnergy` thing. (well there are a few exceptions, Turbines don't consume energy, Algae Pond seems to not overclock in the first place)

**Comment by eigenraven** [comment]
Even if there is more, this fix is fine to merge as-is, and more similar fix PRs can be easily made if tickets get opened

**Comment by draknyte1** [comment]
> I checked all overrides for `checkRecipeGeneric(ItemStack[] aItemInputs, FluidStack[] aFluidInputs, int aMaxParallelRecipes, int aEUPercent, int aSpeedBonusPercent, int aOutputChanceRoll)` and `checkRecipeGeneric(ItemStack[] aItemInputs, FluidStack[] aFluidInputs, int aMaxParallelRecipes, int aEUPercent, int aSpeedBonusPercent, int aOutputChanceRoll, GT_Recipe aRecipe)`, and no problem found for `tEnergy` thing. (well there are a few exceptions, Turbines don't consume energy, Algae Pond seems to not overclock in the first place)

Some just override checkRecipe(aStack) and have the code there. Iirc.

**Pull request merged**
