### PR TITLE
control circuits should not be 0

### PR DESCRIPTION
**Pull request by Dream-Master**
Change recipes using Circuit 0 in their recipes #9818
* https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9818

### CODE REVIEW

**Comment by draknyte1** [comment]
These are intentionally 0.. why change them?

**Comment by Dream-Master** [comment]
Circuit 0 should be the default setting not used for any recipe

**Comment by Dream-Master** [comment]
we have enough nummbers free. If not we can add circuit 25-48

**Comment by draknyte1** [comment]
> Circuit 0 should be the default setting not used for any recipe

Maybe in your opinion, but as the one who added the recipes it was wholly intentional. Changing them because you don’t like the use of 0 is silly. 0 is a valid circuit number and there is no reason it can’t be used.

**Review by Elisis — APPROVED** [review]

**Comment by Dream-Master** [comment]
its more because the circuit programmer not using 0 and logical there is no other mod use now circuit 0 we should change that.
I dont touche the code much only cosmetic things

**Pull request merged**
