### PR TITLE
Fix NPE with reflection

### LINKED ISSUE #10429: player kicked from server when hit by radiation debuff
### Your GTNH Discord Username

NoXъ # 0667

### Your Pack Version

2.1.2.3qf

### Your Server

private

### Type of Server

Vanilla Forge

### Your Actions

Forget to put on orange suit, take something radioactive (plutonium dust, for example) and try to sleep on bed.

### Crash Report

The player wil be kicked from server instead of taking damage from radiation.
[server-kick-log.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8825383/server-kick-log.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

### PR DESCRIPTION
**Pull request by miozune**
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10429

### CODE REVIEW

**Comment by draknyte1** [comment]
The issue should probably be fixed here. https://github.com/GTNewHorizons/GTplusplus/blob/0c63ed37dccd0b914f1f4f6cfc6385177d6d7f1b/src/main/java/gtPlusPlus/core/handler/events/PlayerSleepEventHandler.java#L22

**Comment by miozune** [comment]
This way all method calls, including current and future reference, will be fixed.

**Review by mitchej123 — APPROVED** [review]

**Comment by draknyte1** [comment]
> This way all method calls, including current and future reference, will be fixed.

setField throwing an exception is a good indicator the field passed in is null due to someone (me) using deobf field names. So the code in question is still broken…

**Comment by miozune** [comment]
I cannot reproduce the crash on my end.

**Pull request merged**
